version: "3.7"
services:
  raspi-finance-convert:
    build:
      context: ./
      args:
       - APP=raspi-finance-convert
       - TIMEZONE=America/Chicago
       - USERNAME=henninb
      dockerfile: Dockerfile
    container_name: raspi-finance-convert
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/raspi-finance-convert/logs
      - ./ssl:/opt/raspi-finance-convert/ssl
      - ./excel_in:/opt/raspi-finance-convert/excel_in
      - ./json_in:/opt/raspi-finance-convert/json_in
      - ./config:/opt/raspi-finance-convert/config
    # env_file:
    #   - env.prod
    #   - env.secrets
    extra_hosts:
      - "hornsup:192.168.100.97"
