server:
  port: ${SERVER_PORT}
  ssl:
    key-store: ${SSL_KEYSTORE}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
spring:
  application:
    name: raspi-finance-convert
  profiles:
    active: prod
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

  # ===============================
  # = DATA SOURCE
  # ===============================
  datasource:
    url: ${DATASOURCE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}
    # testWhileIdle to persist the connection when idle for a long period of time
    tomcat:
      test-While-Idle: true
      validation-Query: SELECT 1
    platform: ${DATASOURCE_PLATFORM}
    continue-On-Error: false
    # enable initialization-mode flag to always if you want to utilize data.sql and schema.sql
    #initialization-mode: always
    initialization-mode: never

# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#      javax:
#        persistence:
#          validation:
#            mode: none
logging:
  config: classpath:logback-spring.xml
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#spring.jpa.hibernate.ddl-auto: none
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
#none is build from schema.sql (no Java classes)
#update only add new tables in the schema.sql (starting from Java classes)

# ===============================
# = Custom Configuration
# ===============================
custom:
  project:
    time-zone: ${TIMEZONE}
    excel-password: ${EXCEL_PASSWORD}
    json-Input-File-Path: ${JSON_FILES_INPUT_PATH}
    excel-Input-File-Path: ${EXCEL_FILES_INPUT_PATH}
    camel-route:
      auto-Start-Route: ${CAMEL_ROUTE_ENABLED}
      json-File-Reader-Route-Id: jsonFileReaderRoute
      json-File-Reader-Route: "file:${JSON_FILES_INPUT_PATH}?delete=true&moveFailed=.failedWithErrors"
      excel-File-Reader-Route-Id: excelFileReaderRoute
      excel-File-Reader-Route: "file:${EXCEL_FILES_INPUT_PATH}?delete=true&moveFailed=.failedWithErrors"
      transaction-To-Database-Route-Id: transactionToDatabaseRoute
      transaction-To-Database-Route: direct:transactionToDatabaseRoute
      json-File-Writer-Route-Id: jsonFileWriterRoute
      json-File-writer-route: direct:jsonFileWriterRoute
      saved-File-Endpoint: "file:${JSON_FILES_INPUT_PATH}/.processed"
      failed-Excel-File-Endpoint: "file:${EXCEL_FILES_INPUT_PATH}/.notExcelAndNotProcessed"
      failed-Json-File-Endpoint: "file:${JSON_FILES_INPUT_PATH}/.notExcelAndNotProcessed"
    credit-accounts:
      - amazon_brian
      - amazon.store_brian
      - amex_brian
      - amex_kari
      - amex.newegg_brian
      - amex.newegg_kari
      - amex.rewards_brian
      - barclay.cash_brian
      - barclay.cash_kari
      - barclays_brian
      - barclays_kari
      - bcu_brian
      - boa_brian
      - boa_kari
      - boa.cash_kari
      - capitalone_brian
      - capitalone_kari
      - chase_brian
      - chase_kari
      - chase.unlimited_kari
      - citi_brian
      - citi.dividend_brian
      - discover_brian
      - discover_kari
      - discoverit_brian
      - firstnational_kari
      - gap_kari
      - goodyear_kari
      - herbergers_kari
      - homedepot_brian
      - homedepot_kari
      - hsbc_brian
      - kohls_kari
      - lowes_brian
      - macys_kari
      - medical_brian
      - menards_brian
      - millsfleet_brian
      - mlb_kari
      - mlb.one_brian
      - mlb.two_brian
      - rakuten_brian
      - rcard_brian
      - suzan_brian
      - target_brian
      - target_kari
      - usbankcash_brian
      - usbankcash_kari
      - wfargocash_brian
      - wfargocash_kari
      - citicash_kari
      - citicash_brian
    excluded-accounts:
      - 401k_brian
      - 401k_kari
      - amazongift_brian
      - giftcards_brian
      - pension_brian
      - pension_kari
      - scottrade_ira_brian
      - vacation_brian
      - vacation_kari

# ===============================
# = Camel
# ===============================
camel:
  springboot:
    name: RaspiFinance
  health.check.routes.enabled: false

# ===============================
# = Health and Metrics
# ===============================
management:
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      influx:
        enabled: true
        auto-create-db: true
        db: metrics
        compressed: false
        uri: http://hornsup:8086
        user-name: henninb
        password: monday1
#elasticsearch:
#  clustername = finance-cluster
#  host = hornsup
#  port = 9300
debug: false
